/**
 * LOINC (Logical Observation Identifiers Names and Codes) Laboratory & Clinical Ontology
 * Standard terminology for Laboratory Diagnostic Tests, Panels, Reference Ranges, and Units of Measure
 */

export interface LoincObservationEntry {
  loincCode: string;
  component: string; // Analyte measured (e.g. "Glucose", "Troponin I.cardiac", "Potassium")
  property: string; // Property type (e.g. "MCnc" = Mass Concentration, "SCnc" = Substance Concentration)
  timeAspect: 'Pt' | '24H' | 'Doc'; // Point in time vs 24 hour collection
  system: string; // Specimen matrix (e.g. "Ser/Plas", "Bld", "Urine", "CSF")
  scaleType: 'Qn' | 'Ord' | 'Nom' | 'Nar'; // Quantitative, Ordinal, Nominal, Narrative
  methodType?: string;
  longCommonName: string;
  class: 'CHEM' | 'HEM/BC' | 'MICRO' | 'TOX' | 'COAG' | 'SERO' | 'RAD';
  standardUnitOfMeasure: string;
  standardReferenceRange: {
    low?: number;
    high?: number;
    unit: string;
    criticalPanicLow?: number;
    criticalPanicHigh?: number;
  };
}

export const MASTER_LOINC_CATALOG: LoincObservationEntry[] = [
  // Clinical Chemistry & Metabolic Panel (CMP / BMP)
  {
    loincCode: '2345-7',
    component: 'Glucose',
    property: 'MCnc',
    timeAspect: 'Pt',
    system: 'Ser/Plas',
    scaleType: 'Qn',
    longCommonName: 'Glucose [Mass/volume] in Serum or Plasma',
    class: 'CHEM',
    standardUnitOfMeasure: 'mg/dL',
    standardReferenceRange: { low: 70, high: 99, unit: 'mg/dL', criticalPanicLow: 45, criticalPanicHigh: 450 },
  },
  {
    loincCode: '2823-3',
    component: 'Potassium',
    property: 'SCnc',
    timeAspect: 'Pt',
    system: 'Ser/Plas',
    scaleType: 'Qn',
    longCommonName: 'Potassium [Moles/volume] in Serum or Plasma',
    class: 'CHEM',
    standardUnitOfMeasure: 'mEq/L',
    standardReferenceRange: { low: 3.5, high: 5.0, unit: 'mEq/L', criticalPanicLow: 2.8, criticalPanicHigh: 6.2 },
  },
  {
    loincCode: '2951-2',
    component: 'Sodium',
    property: 'SCnc',
    timeAspect: 'Pt',
    system: 'Ser/Plas',
    scaleType: 'Qn',
    longCommonName: 'Sodium [Moles/volume] in Serum or Plasma',
    class: 'CHEM',
    standardUnitOfMeasure: 'mEq/L',
    standardReferenceRange: { low: 135, high: 145, unit: 'mEq/L', criticalPanicLow: 120, criticalPanicHigh: 160 },
  },
  {
    loincCode: '2075-0',
    component: 'Chloride',
    property: 'SCnc',
    timeAspect: 'Pt',
    system: 'Ser/Plas',
    scaleType: 'Qn',
    longCommonName: 'Chloride [Moles/volume] in Serum or Plasma',
    class: 'CHEM',
    standardUnitOfMeasure: 'mEq/L',
    standardReferenceRange: { low: 96, high: 106, unit: 'mEq/L', criticalPanicLow: 80, criticalPanicHigh: 120 },
  },
  {
    loincCode: '2028-9',
    component: 'Carbon dioxide',
    property: 'SCnc',
    timeAspect: 'Pt',
    system: 'Ser/Plas',
    scaleType: 'Qn',
    longCommonName: 'Carbon dioxide, total [Moles/volume] in Serum or Plasma',
    class: 'CHEM',
    standardUnitOfMeasure: 'mEq/L',
    standardReferenceRange: { low: 22, high: 29, unit: 'mEq/L', criticalPanicLow: 10, criticalPanicHigh: 40 },
  },
  {
    loincCode: '2160-0',
    component: 'Creatinine',
    property: 'MCnc',
    timeAspect: 'Pt',
    system: 'Ser/Plas',
    scaleType: 'Qn',
    longCommonName: 'Creatinine [Mass/volume] in Serum or Plasma',
    class: 'CHEM',
    standardUnitOfMeasure: 'mg/dL',
    standardReferenceRange: { low: 0.7, high: 1.3, unit: 'mg/dL', criticalPanicHigh: 5.0 },
  },
  {
    loincCode: '3094-0',
    component: 'Urea nitrogen',
    property: 'MCnc',
    timeAspect: 'Pt',
    system: 'Ser/Plas',
    scaleType: 'Qn',
    longCommonName: 'Blood urea nitrogen (BUN) [Mass/volume] in Serum or Plasma',
    class: 'CHEM',
    standardUnitOfMeasure: 'mg/dL',
    standardReferenceRange: { low: 7, high: 20, unit: 'mg/dL', criticalPanicHigh: 80 },
  },
  {
    loincCode: '17861-6',
    component: 'Calcium',
    property: 'MCnc',
    timeAspect: 'Pt',
    system: 'Ser/Plas',
    scaleType: 'Qn',
    longCommonName: 'Calcium [Mass/volume] in Serum or Plasma',
    class: 'CHEM',
    standardUnitOfMeasure: 'mg/dL',
    standardReferenceRange: { low: 8.5, high: 10.2, unit: 'mg/dL', criticalPanicLow: 6.5, criticalPanicHigh: 13.0 },
  },
  {
    loincCode: '1975-2',
    component: 'Bilirubin.total',
    property: 'MCnc',
    timeAspect: 'Pt',
    system: 'Ser/Plas',
    scaleType: 'Qn',
    longCommonName: 'Bilirubin.total [Mass/volume] in Serum or Plasma',
    class: 'CHEM',
    standardUnitOfMeasure: 'mg/dL',
    standardReferenceRange: { low: 0.1, high: 1.2, unit: 'mg/dL', criticalPanicHigh: 15.0 },
  },
  {
    loincCode: '1751-7',
    component: 'Albumin',
    property: 'MCnc',
    timeAspect: 'Pt',
    system: 'Ser/Plas',
    scaleType: 'Qn',
    longCommonName: 'Albumin [Mass/volume] in Serum or Plasma',
    class: 'CHEM',
    standardUnitOfMeasure: 'g/dL',
    standardReferenceRange: { low: 3.5, high: 5.0, unit: 'g/dL', criticalPanicLow: 1.5 },
  },
  {
    loincCode: '1920-8',
    component: 'Aspartate aminotransferase (AST)',
    property: 'CCnc',
    timeAspect: 'Pt',
    system: 'Ser/Plas',
    scaleType: 'Qn',
    longCommonName: 'Aspartate aminotransferase [Enzymatic activity/volume] in Serum or Plasma',
    class: 'CHEM',
    standardUnitOfMeasure: 'U/L',
    standardReferenceRange: { low: 10, high: 40, unit: 'U/L', criticalPanicHigh: 1000 },
  },
  {
    loincCode: '1742-6',
    component: 'Alanine aminotransferase (ALT)',
    property: 'CCnc',
    timeAspect: 'Pt',
    system: 'Ser/Plas',
    scaleType: 'Qn',
    longCommonName: 'Alanine aminotransferase [Enzymatic activity/volume] in Serum or Plasma',
    class: 'CHEM',
    standardUnitOfMeasure: 'U/L',
    standardReferenceRange: { low: 7, high: 56, unit: 'U/L', criticalPanicHigh: 1000 },
  },
  {
    loincCode: '6768-6',
    component: 'Alkaline phosphatase',
    property: 'CCnc',
    timeAspect: 'Pt',
    system: 'Ser/Plas',
    scaleType: 'Qn',
    longCommonName: 'Alkaline phosphatase [Enzymatic activity/volume] in Serum or Plasma',
    class: 'CHEM',
    standardUnitOfMeasure: 'U/L',
    standardReferenceRange: { low: 44, high: 147, unit: 'U/L' },
  },

  // Cardiac Biomarkers & Critical Care
  {
    loincCode: '89579-7',
    component: 'Troponin I.cardiac.high sensitivity',
    property: 'MCnc',
    timeAspect: 'Pt',
    system: 'Ser/Plas',
    scaleType: 'Qn',
    longCommonName: 'Troponin I.cardiac.high sensitivity [Mass/volume] in Serum or Plasma',
    class: 'CHEM',
    standardUnitOfMeasure: 'ng/L',
    standardReferenceRange: { low: 0, high: 14, unit: 'ng/L', criticalPanicHigh: 52 },
  },
  {
    loincCode: '33762-6',
    component: 'Natriuretic peptide.B prohormone N-Terminal (NT-proBNP)',
    property: 'MCnc',
    timeAspect: 'Pt',
    system: 'Ser/Plas',
    scaleType: 'Qn',
    longCommonName: 'NT-proBNP [Mass/volume] in Serum or Plasma',
    class: 'CHEM',
    standardUnitOfMeasure: 'pg/mL',
    standardReferenceRange: { low: 0, high: 125, unit: 'pg/mL', criticalPanicHigh: 1800 },
  },
  {
    loincCode: '2524-7',
    component: 'Lactate',
    property: 'MCnc',
    timeAspect: 'Pt',
    system: 'BldV',
    scaleType: 'Qn',
    longCommonName: 'Lactate [Moles/volume] in Venous blood',
    class: 'CHEM',
    standardUnitOfMeasure: 'mmol/L',
    standardReferenceRange: { low: 0.5, high: 2.0, unit: 'mmol/L', criticalPanicHigh: 4.0 },
  },

  // Hematology & Coagulation
  {
    loincCode: '6690-2',
    component: 'Leukocytes (WBC)',
    property: 'NCnc',
    timeAspect: 'Pt',
    system: 'Bld',
    scaleType: 'Qn',
    longCommonName: 'Leukocytes [#/volume] in Blood by Automated count',
    class: 'HEM/BC',
    standardUnitOfMeasure: '10*3/uL',
    standardReferenceRange: { low: 4.5, high: 11.0, unit: '10*3/uL', criticalPanicLow: 1.5, criticalPanicHigh: 30.0 },
  },
  {
    loincCode: '718-7',
    component: 'Hemoglobin',
    property: 'MCnc',
    timeAspect: 'Pt',
    system: 'Bld',
    scaleType: 'Qn',
    longCommonName: 'Hemoglobin [Mass/volume] in Blood',
    class: 'HEM/BC',
    standardUnitOfMeasure: 'g/dL',
    standardReferenceRange: { low: 12.0, high: 17.5, unit: 'g/dL', criticalPanicLow: 7.0, criticalPanicHigh: 20.0 },
  },
  {
    loincCode: '4544-3',
    component: 'Hematocrit',
    property: 'VFr',
    timeAspect: 'Pt',
    system: 'Bld',
    scaleType: 'Qn',
    longCommonName: 'Hematocrit [Volume Fraction] of Blood',
    class: 'HEM/BC',
    standardUnitOfMeasure: '%',
    standardReferenceRange: { low: 36, high: 50, unit: '%', criticalPanicLow: 21, criticalPanicHigh: 60 },
  },
  {
    loincCode: '777-3',
    component: 'Platelets',
    property: 'NCnc',
    timeAspect: 'Pt',
    system: 'Bld',
    scaleType: 'Qn',
    longCommonName: 'Platelets [#/volume] in Blood by Automated count',
    class: 'HEM/BC',
    standardUnitOfMeasure: '10*3/uL',
    standardReferenceRange: { low: 150, high: 450, unit: '10*3/uL', criticalPanicLow: 20, criticalPanicHigh: 1000 },
  },
  {
    loincCode: '5902-2',
    component: 'Prothrombin time (PT/INR)',
    property: 'RelTime',
    timeAspect: 'Pt',
    system: 'Plas',
    scaleType: 'Qn',
    longCommonName: 'Prothrombin time (PT) in Platelet poor plasma by Coagulation assay',
    class: 'COAG',
    standardUnitOfMeasure: 'INR',
    standardReferenceRange: { low: 0.9, high: 1.1, unit: 'INR', criticalPanicHigh: 5.0 },
  },
  {
    loincCode: '3173-2',
    component: 'aPTT',
    property: 'Time',
    timeAspect: 'Pt',
    system: 'Plas',
    scaleType: 'Qn',
    longCommonName: 'Activated partial thromboplastin time (aPTT) in Platelet poor plasma',
    class: 'COAG',
    standardUnitOfMeasure: 'seconds',
    standardReferenceRange: { low: 25, high: 35, unit: 'seconds', criticalPanicHigh: 100 },
  },
];
